#bash
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 5
firefox https://www.youtube.com/channel/UCiaC2jmRppozuqp1-UfDFrw
sleep 10