#bash
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 5
firefox https://www.youtube.com/c/agungmujiono
sleep 10